name: Test School Python 02

on:
  pull_request:
    branches: ["main", "master"]

jobs:
  test-project:
    uses: cx-actions-2025/fm-actions/.github/workflows/school-python2.yaml@0238001d4748157ac3dc659bc20d37734ebfb121
    with:
        team-name: ${{ vars.TEAM_NAME }}
    secrets:
        test-repo: ${{ secrets.TEST_REPO }}
        auth-token: ${{ secrets.AUTH_TOKEN }}
        backend-url: ${{ secrets.BACKEND_URL }}
        auth-key: ${{ secrets.AUTH_KEY }}

